# requestURL = commandHandler		mapping
/mvc/board/list.htm= days07.mvc.board.command.ListHandler
/mvc/board/write.htm= days07.mvc.board.command.WriteHandler
/mvc/board/view.htm= days07.mvc.board.command.ViewHandler
/mvc/board/edit.htm= days07.mvc.board.command.EditHandler
/mvc/board/delete.htm= days07.mvc.board.command.DeleteHandler
#/mvc/member/login.htm= days07.mvc.member.command.LoginHandler